@echo off
echo Stopper eksisterende server...
taskkill /f /im node.exe 2>nul
timeout /t 2 /nobreak > nul
echo Starter server på nytt...
cd /d "C:\Users\holge\Documents\Annet\project\backend"
echo Starting Node.js server...
node src/server.js
